version: '3.8'

services:
  # RabbitMQ for message broker (Enterprise Scale)
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: hexar-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: hexar_user
      RABBITMQ_DEFAULT_PASS: hexar_password
      RABBITMQ_DEFAULT_VHOST: hexar_vhost
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis for caching and session storage
  redis:
    image: redis:7-alpine
    container_name: hexar-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # PostgreSQL database (via Supabase in production, local for development)
  postgres:
    image: postgres:15-alpine
    container_name: hexar-postgres
    environment:
      POSTGRES_DB: hexar_dev
      POSTGRES_USER: hexar_user
      POSTGRES_PASSWORD: hexar_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hexar_user -d hexar_dev"]
      interval: 10s
      timeout: 5s
      retries: 3

  # FastAPI backend with multi-agent system
  backend:
    build:
      context: ./hexar-backend
      dockerfile: Dockerfile
    container_name: hexar-backend
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://hexar_user:hexar_password@rabbitmq:5672/hexar_vhost
      - DATABASE_URL=postgresql://hexar_user:hexar_password@postgres:5432/hexar_dev
      - MESSAGE_BROKER_TYPE=${MESSAGE_BROKER_TYPE:-rabbitmq}  # rabbitmq or redis for backward compatibility
    volumes:
      - ./hexar-backend:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Celery worker for async agent tasks
  celery-worker:
    build:
      context: ./hexar-backend
      dockerfile: Dockerfile
    container_name: hexar-celery-worker
    command: celery -A mcp.message_broker worker --loglevel=info
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://hexar_user:hexar_password@rabbitmq:5672/hexar_vhost
      - DATABASE_URL=postgresql://hexar_user:hexar_password@postgres:5432/hexar_dev
      - MESSAGE_BROKER_TYPE=${MESSAGE_BROKER_TYPE:-rabbitmq}  # rabbitmq or redis for backward compatibility
    volumes:
      - ./hexar-backend:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      backend:
        condition: service_healthy

  # Next.js frontend
  frontend:
    build:
      context: ./hexar-frontend
      dockerfile: Dockerfile
    container_name: hexar-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_AGENT_WEBSOCKET_URL=ws://backend:8000/agents/ws
      - NEXT_PUBLIC_API_URL=http://backend:8000
    volumes:
      - ./hexar-frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      backend:
        condition: service_healthy

  # Agent monitoring dashboard (optional)
  monitoring:
    image: prom/prometheus:latest
    container_name: hexar-monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'

volumes:
  rabbitmq_data:
  redis_data:
  postgres_data:
  prometheus_data:

networks:
  default:
    name: hexar-network